--- S_EMP COMPLETE
SELECT 
E.FIRST_NAME,
E.LAST_NAME,
E.USERID,
E.START_DATE,
E.COMMENTS,
E.TITLE,
E.SALARY,
E.COMMISSION_PCT,
D.NAME AS DEPARTMENT,
R.NAME AS REGION
FROM S_EMP E, S_DEPT D, S_REGION R
WHERE E.DEPT_ID = D.ID AND E.REGION_ID = R.ID
GROUP BY 
E.FIRST_NAME,
E.LAST_NAME,
E.USERID,
E.START_DATE,
E.COMMENTS,
E.TITLE,
E.SALARY,
E.COMMISSION_PCT,
D.NAME,
R.NAME;


---DATOSPERSONALES COMPLETO
SELECT
DP.*,
G.GENERO AS GENERO,
TD.TIPO
FROM DATOSPERSONALES DP, GENERO G, TIPODOCUMENTO TD
WHERE DP.IDGENERO = G.IDGENERO AND DP.IDDOCUMENTO = TD.IDDOCUMENT;


INSERT INTO DATOSPERSONALES (IDPERSONA,IDGENERO,IDDOCUMNETO,NOMBRE,DOCUMENTO,EDAD,EMAIL,CELULAR,DIRECCION) VALUES (NULL,32,22,'oscar',112323,12,'asd@gmail.com',32343242,'calle1234-2');
